title: Differential Privacy Deployments Registry
email: info@opendp.org
description: >-
  This resource aims to support practitioners deploying differential privacy in practice.
  It endeavors to leave the reader with a clearer intuition, responsible guidance,
  and case studies of privacy budgets used by organizations today.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://registry.opendp.org/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - content/overview.md
markdown: kramdown # The default: passes <script> tags through verbatim.

exclude:
  - eslint.config.mjs
  - node_modules/
  - package-lock.json
  - package.json
  - vendor
