title: Differential Privacy Deployments Registry
email: info@opendp.org
description: >-
  This resource aims to support practitioners deploying differential privacy in practice.
  It endeavors to leave the reader with a clearer intuition, responsible guidance,
  and case studies of privacy budgets used by organizations today.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://registry.opendp.org/"

# Build settings
theme: minima
plugins:
  - jekyll-feed
header_pages:
  - content/overview.md


exclude:
  - tests
  - .venv
  - vendor
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
